
// import { Readex_Pro } from "next/font/google";
// import "./globals.css";

// import Providers from "../language/Providers.jsx";
// import { cookies } from "next/headers";

// const readexPro = Readex_Pro({
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Zetime",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const cookieStore = await cookies();
//   const lang = cookieStore.get("lang")?.value || "ar";
//   const dir = lang === "ar" ? "rtl" : "ltr";

//   return (
//     <html lang={lang} dir={dir}>
//       <body className={`${readexPro.className} antialiased`}>
//         <Providers lang={lang}>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
// -------------------------------------------------------------------------
// import { Cairo } from "next/font/google";
// import "./globals.css";

// import Providers from "../language/Providers.jsx";
// import { cookies } from "next/headers";

// const cairo = Cairo({
//   subsets: ["arabic", "latin"],
//   weight: ["400", "500", "600", "700"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Zetime",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const cookieStore = await cookies();
//   const lang = cookieStore.get("lang")?.value || "ar";
//   const dir = lang === "ar" ? "rtl" : "ltr";

//   return (
//     <html lang={lang} dir={dir}>
//       <body className={`${cairo.className} antialiased`}>
//         <Providers lang={lang}>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
//-----------------------------------------------------------------------
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";

import Providers from "../language/Providers.jsx";
import { cookies } from "next/headers";

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Zetime",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const lang = cookieStore.get("lang")?.value || "ar";
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={lang} dir={dir}>
      <body className={`${ibmPlexSansArabic.className} antialiased`}>
        <Providers lang={lang}>
          {children}
        </Providers>
      </body>
    </html>
  );
}