// import { Readex_Pro } from "next/font/google";
// import "./globals.css";


// const readexPro = Readex_Pro({
//   variable: "--font-readex-pro",
//   subsets: ["latin"], 
// });

// export const metadata = {
//   title: "Zetime",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="ar" dir="rtl">
//       <body
//         className={`${readexPro.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { Readex_Pro } from "next/font/google";
import "./globals.css";

import Providers from "../language/Providers.jsx"
import i18n from "../language/i18n";
import { cookies } from "next/headers";

const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zetime",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const lang = cookieStore.get("lang")?.value || "ar";
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={lang} dir={dir}>
      <body className={`${readexPro.variable} antialiased`}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}

